# Generated by Django 4.1.6 on 2023-02-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0002_sucursal_delete_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='DNI',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='DNI_cliente',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='fecha_de_reservacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='numero_mesa',
            field=models.IntegerField(),
        ),
    ]
