# Generated by Django 4.1.6 on 2023-02-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0003_alter_cliente_dni_alter_reservacion_dni_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='Ciudad',
            field=models.CharField(choices=[('Buenos Aires Argentina', 'Buenos Aires Argentina'), ('Lima Peru', 'Lima Peru'), ('Bogota Colombia', 'Bogota Colombia'), ('Sao Paulo Brasil', 'Sao Paulo Brasil')], default='Buenos Aires Argentina', max_length=30),
        ),
    ]
