# Generated by Django 4.1.6 on 2023-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0004_remove_sucursal_ciudad_sucursal_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
