# Generated by Django 4.1.6 on 2023-02-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0005_alter_cliente_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservacion',
            old_name='DNI_cliente',
            new_name='DNI',
        ),
    ]
