# Generated by Django 4.1.6 on 2023-02-21 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resto', '0007_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='usuario',
        ),
    ]
